let token=localStorage.getItem('token'),currentUser=null,currentCharacter=null,socket=io();
if(token){showGame();loadCharacters();loadFriends()}
async function api(e,t='GET',a=null){const n={method:t,headers:{'Content-Type':'application/json'}};if(token)n.headers.Authorization='Bearer '+token;if(a)n.body=JSON.stringify(a);const r=await fetch('/api'+e,n);return r.json()}
function showMessage(e,t='success'){const a=document.createElement('div');a.className='message '+t;a.textContent=e;document.getElementById('messages').appendChild(a);setTimeout(()=>a.remove(),4000)}
async function register(){const e=document.getElementById('username').value,t=document.getElementById('password').value,a=await api('/register','POST',{username:e,password:t});if(a.token){token=a.token;currentUser=a.user;localStorage.setItem('token',token);document.getElementById('player-name').textContent=a.user.username;showGame();showMessage('✅ Conta criada!')}else showMessage(a.error,'error')}
async function login(){const e=document.getElementById('username').value,t=document.getElementById('password').value,a=await api('/login','POST',{username:e,password:t});if(a.token){token=a.token;currentUser=a.user;localStorage.setItem('token',token);document.getElementById('player-name').textContent=a.user.username;if(a.user.isAdmin){document.getElementById('admin-badge').classList.remove('hidden');document.getElementById('admin-btn').classList.remove('hidden')}showGame();loadCharacters();loadFriends();showMessage('✅ Login realizado!')}else showMessage(a.error,'error')}
function logout(){token=null;currentUser=null;localStorage.removeItem('token');document.getElementById('auth-section').classList.remove('hidden');document.getElementById('game-section').classList.add('hidden');showMessage('👋 Logout!')}
function showGame(){document.getElementById('auth-section').classList.add('hidden');document.getElementById('game-section').classList.remove('hidden')}
async function createCharacter(){const e=document.getElementById('char-name').value,t=document.getElementById('char-class').value;if(!e)return showMessage('Digite um nome!','error');const a=await api('/characters','POST',{name:e,characterClass:t});if(a.message){showMessage('✅ '+a.message);document.getElementById('char-name').value='';loadCharacters()}else showMessage(a.error,'error')}
async function loadCharacters(){const e=await api('/characters'),t=document.getElementById('characters-list');if(e.length===0){t.innerHTML='<p>Nenhum personagem criado.</p>';return}t.innerHTML=e.map(c=>'<div class="character-card"><h4>'+c.name+' - '+c.class+' (Nível '+c.level+')</h4><p style="color:#ffd700">⚡ '+c.special_power+'</p><div class="stats"><div class="stat">❤️ '+c.hp+'/'+c.max_hp+'</div><div class="stat">💙 '+c.mp+'/'+c.max_mp+'</div><div class="stat">⭐ '+c.exp+'/'+(c.level*100)+'</div><div class="stat">💰 '+c.gold+'</div><div class="stat">💪 '+c.str+'</div><div class="stat">🧠 '+c.int+'</div><div class="stat">⚡ '+c.agi+'</div></div><button class="btn btn-danger" onclick="startBattle('+c.id+')">Batalhar PvE</button></div>').join('')}
function startBattle(e){currentCharacter=e;document.getElementById('battle-section').classList.remove('hidden');document.getElementById('battle-info').innerHTML='<p style="font-size:1.5em">🐉 Um Goblin selvagem apareceu! (60 HP)</p>';document.getElementById('battle-result').innerHTML=''}
async function battle(e){if(!currentCharacter)return;const t=await api('/battle/'+currentCharacter,'POST',{action:e});if(t.error)return showMessage(t.error,'error');let a='<p style="font-size:1.2em">'+t.message+'</p>';a+='<p>🐉 Goblin HP: <span style="color:#f44336">'+t.enemyHp+'</span></p>';a+='<p>👤 Seu HP: <span style="color:#4CAF50">'+t.playerHp+'</span></p>';if(t.cooldown>0)a+='<p>⏳ Cooldown: '+t.cooldown+' turnos</p>';if(t.levelUp)a+='<p style="color:#ffd700;font-size:1.5em">🎉 LEVEL UP!</p>';if(t.victory||t.defeat){a+='<button class="btn btn-secondary" onclick="endBattle()">Nova Batalha</button>';loadCharacters()}document.getElementById('battle-result').innerHTML=a}
function endBattle(){document.getElementById('battle-section').classList.add('hidden');currentCharacter=null}
async function loadOnlinePlayers(){const e=await api('/characters/online'),t=document.getElementById('online-players');if(e.length===0){t.innerHTML='<p>Nenhum jogador online.</p>';return}t.innerHTML=e.map(p=>'<div class="player-card"><h4>'+p.name+' ('+p.username+') - '+p.class+' Nv.'+p.level+'</h4><p>💪 STR: '+p.str+' | 🧠 INT: '+p.int+' | ⚡ AGI: '+p.agi+'</p><button class="btn btn-warning" onclick="challengePlayer('+p.id+')">⚔️ Desafiar</button></div>').join('')}
async function challengePlayer(e){const t=await api('/characters');if(t.length===0)return showMessage('Crie um personagem primeiro!','error');const a=t[0].id,n=await api('/pvp/challenge','POST',{myCharId:a,opponentCharId:e});if(n.error)return showMessage(n.error,'error');let s=n.victory?'🎉 VITÓRIA!':'😢 DERROTA!';s+='\n+'+n.expGain+' EXP, +'+n.goldGain+' ouro\n\nRounds:\n'+n.rounds.join('\n');alert(s);loadCharacters()}
async function addFriend(){const e=document.getElementById('friend-username').value;if(!e)return showMessage('Digite o nome!','error');const t=await api('/friends','POST',{username:e});if(t.message){showMessage('✅ '+t.message);document.getElementById('friend-username').value='';loadFriends()}else showMessage(t.error,'error')}
async function loadFriends(){const e=await api('/friends'),t=document.getElementById('friends-list'),a=document.getElementById('chat-friend-select');if(e.length===0){t.innerHTML='<p>Nenhum amigo adicionado.</p>';return}t.innerHTML=e.map(f=>'<div style="padding:12px;margin:8px 0;background:rgba(255,255,255,0.1);border-radius:8px">👤 '+f.username+'<button class="btn btn-primary" style="padding:8px 16px;margin-left:10px" onclick="openChat('+f.id+',\''+f.username+'\')">💬 Chat</button></div>').join('');a.innerHTML='<option value="">Selecione um amigo</option>'+e.map(f=>'<option value="'+f.id+'">'+f.username+'</option>').join('')}
let currentChatFriend=null;
function openChat(e,t){currentChatFriend=e;document.getElementById('chat-friend-select').value=e;loadMessages(e)}
async function loadMessages(e){if(!e)return;const t=await api('/messages/'+e),a=document.getElementById('chat-messages');a.innerHTML=t.map(m=>'<div class="chat-message" style="background:'+(m.from_user_id==currentUser.id?'rgba(33,150,243,0.3)':'rgba(76,175,80,0.3)')+'"><strong>'+m.from_username+':</strong> '+m.message+'</div>').join('');a.scrollTop=a.scrollHeight}
async function sendMessage(){const e=document.getElementById('chat-friend-select').value,t=document.getElementById('chat-input').value;if(!e||!t)return showMessage('Selecione um amigo e digite uma mensagem!','error');await api('/messages','POST',{toUserId:e,message:t});document.getElementById('chat-input').value='';loadMessages(e)}
function toggleAdmin(){const e=document.getElementById('admin-panel');e.classList.toggle('hidden');if(!e.classList.contains('hidden')){loadAdminUsers();loadAdminChars()}}
async function loadAdminUsers(){const e=await api('/admin/users'),t=document.getElementById('admin-users-list');t.innerHTML=e.map(u=>'<div style="padding:10px;margin:5px 0;background:rgba(255,255,255,0.1);border-radius:5px"><strong>'+u.username+'</strong> - '+(u.is_banned?'🚫 Banido':'✅ Ativo')+'<button class="btn '+(u.is_banned?'btn-primary':'btn-danger')+'" style="padding:5px 10px" onclick="'+(u.is_banned?'unbanUser':'banUser')+'('+u.id+')">'+(u.is_banned?'Desbanir':'Banir')+'</button></div>').join('')}
async function loadAdminChars(){const e=await api('/admin/characters'),t=document.getElementById('admin-chars-list');t.innerHTML=e.map(c=>'<div style="padding:10px;margin:5px 0;background:rgba(255,255,255,0.1);border-radius:5px"><strong>'+c.name+'</strong> ('+c.username+') - Nv.'+c.level+'<input type="number" id="level-'+c.id+'" value="'+c.level+'" style="width:60px;padding:5px;margin:0 5px"><button class="btn btn-warning" style="padding:5px 10px" onclick="setLevel('+c.id+')">Alterar</button></div>').join('')}
async function banUser(e){await api('/admin/ban/'+e,'POST');showMessage('✅ Usuário banido');loadAdminUsers()}
async function unbanUser(e){await api('/admin/unban/'+e,'POST');showMessage('✅ Usuário desbanido');loadAdminUsers()}
async function setLevel(e){const t=document.getElementById('level-'+e).value;await api('/admin/setlevel','POST',{charId:e,level:t});showMessage('✅ Nível alterado');loadAdminChars()}
socket.on('new_message',e=>{if(currentChatFriend&&(e.from==currentChatFriend||e.to==currentChatFriend))loadMessages(currentChatFriend)});